apiVersion: v1
kind: Service
metadata:
  name: rpc-service
spec:
  type: LoadBalancer
  selector:
    app: rpc-service
    version: v1
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
