apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service
spec:
  selector:
    matchLabels:
      app: web-service
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: web-service
        version: v1
    spec:
      containers:
      - name: web-service
        image: "gcr.io/distributed-system-course/web-service:latest"
        ports:
        - containerPort: 8080